[관련 내용 링크 참고](https://velog.io/@shong676/Colab%EA%B3%BC-GitHub-%EC%97%B0%EB%8F%99%ED%95%98%EA%B8%B0)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

cd /content/drive/MyDrive/개인_프로젝트/titanic_PJT

!git config --global user.email 'riminiop@gmail.com'
!git config --global user.name 'PJH222'

!git add --all

!git commit -m '1'
!git push

In [25]:
import seaborn as sns
import pandas as pd
import numpy as np

df = pd.read_csv("/content/train.csv", sep=",")
test_df = pd.read_csv("/content/train.csv", sep=",")

# df.head()
# test_df.head()

# 데이터 셋 설명
```
survival : 생존 여부, 1 생존 / 0 생존X
pclass : 티켓 등급, 1/2/3
sibsp : 타이타닉호에 탑승한 형제자매/배우자 수
parch : 타이타닉호에 탑승한 부모/자녀 수
cabin : 객실 번호
fare : 여객 운임 요금
embarked : 승선항 (승선했던 항구), 	C = 셰르부르, Q = 퀸스타운, S = 사우샘프턴
```

In [12]:
import pandas as pd
import numpy as np

# df의 통계정 정보 출력
# df.describe()



# df의 결측치 개수
df.isnull().sum()
#   현재 age, Cabin, embarked 에서 결측치가 확인이 된다.

# df의 데이터 개수
len(df)

# df의 칼럼 종류
df.columns

# df.isnull().mean() * 100

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

#### 결측치 각 칼럼별 비율
```
PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64
```
---

우선 결측치를 어떻게 해결할지 고민해보자.
`Age`는 `int`형, `Cabin`과 `embarked`는 `string`이다.

Age결측치 비율은 20%를 차지하므로 __대체__하고,
Cabin 결측치 비율이 77%이므로 이는 __칼럼을 삭제__하는 것이 나을 것으로 보인다.
마지막으로 embarked 결측치 비율은 0.2%인데 __대체__ 해야 할 것으로 보인다.

시간과 관련한 데이터가 없으므로,
평균값 / 최빈값 대체 / MICE를 활용하여 대체를 수행하면 될 것 같다.

# 데이터 전처리

In [34]:
# df = df.drop("Cabin",axis = 1)
# test_df = test_df.drop("Cabin", axis = 1)
# 한번 수행하면 칼럼이 삭제되므로 2번 이상 실행할 수 없으므로 유의하자.
# df, test_df

In [38]:
df = pd.read_csv("/content/train.csv", sep=",")

# return이 어떻게 되는지 이해 할 것
df.fillna({'Age':df['Age'].mode()[0],
           'Embarked':df['Embarked'].mode()[0]}, inplace=True)
df_mode = df
# df_mode
# 최빈값으로 대체한 df

In [46]:
print(df_mode)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female  24.0      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [42]:
df = pd.read_csv("/content/train.csv", sep=",")

# return이 어떻게 되는지 이해 할 것
df.fillna({'Age':df['Age'].mean(),
           'Embarked':df['Embarked'].mode()[0]},inplace=True)
df_mean_mode = df

In [57]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

df = pd.read_csv("/content/train.csv", sep=",")
df.fillna({'Embarked':df['Embarked'].mode()[0]}, inplace=True)

imputer_mice = IterativeImputer(random_state=32)
df_mice = pd.DataFrame(imputer_mice.fit_transform(df.loc['PassengerId' ,'Age']), columns=df.columns)

KeyError: 'PassengerId'