[관련 내용 링크 참고](https://velog.io/@shong676/Colab%EA%B3%BC-GitHub-%EC%97%B0%EB%8F%99%ED%95%98%EA%B8%B0)

In [ ]:
cd /content/drive/MyDrive/개인_프로젝트/titanic_PJT

/content/drive/MyDrive/개인_프로젝트/titanic_PJT

In [4]:
from google.colab import drive
drive.mount('/content/drive')

# !cd /content/drive/MyDrive/개인_프로젝트/titanic_PJT

!git config --global user.email 'riminiop@gmail.com'
!git config --global user.name 'PJH222'

!git add --all

!git commit -m '1'
!git push

Mounted at /content/drive
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git

In [6]:
import seaborn as sns
import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/개인_프로젝트/titanic_PJT/train.csv", sep=",")
test_df = pd.read_csv("/content/drive/MyDrive/개인_프로젝트/titanic_PJT/test.csv", sep=",")

# df.head()
# test_df.head()

# 데이터 셋 설명
```
survival : 생존 여부, 1 생존 / 0 생존X
pclass : 티켓 등급, 1/2/3
sibsp : 타이타닉호에 탑승한 형제자매/배우자 수
parch : 타이타닉호에 탑승한 부모/자녀 수
cabin : 객실 번호
fare : 여객 운임 요금
embarked : 승선항 (승선했던 항구), 	C = 셰르부르, Q = 퀸스타운, S = 사우샘프턴
```

In [ ]:
import pandas as pd
import numpy as np

# df의 통계정 정보 출력
# df.describe()



# df의 결측치 개수
df.isnull().sum()
#   현재 age, Cabin, embarked 에서 결측치가 확인이 된다.

# df의 데이터 개수
len(df)

# df의 칼럼 종류
df.columns

# df.isnull().mean() * 100

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

#### 결측치 각 칼럼별 비율
```
PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64
```
---

우선 결측치를 어떻게 해결할지 고민해보자.
`Age`는 `int`형, `Cabin`과 `embarked`는 `string`이다.

Age결측치 비율은 20%를 차지하므로 __대체__하고,
Cabin 결측치 비율이 77%이므로 이는 __칼럼을 삭제__하는 것이 나을 것으로 보인다.
마지막으로 embarked 결측치 비율은 0.2%인데 __대체__ 해야 할 것으로 보인다.

시간과 관련한 데이터가 없으므로,
평균값 / 최빈값 대체 / MICE를 활용하여 대체를 수행하면 될 것 같다.

# 데이터 전처리

In [ ]:
# df = df.drop("Cabin",axis = 1)
# test_df = test_df.drop("Cabin", axis = 1)
# 한번 수행하면 칼럼이 삭제되므로 2번 이상 실행할 수 없으므로 유의하자.
# df, test_df

In [51]:
df = pd.read_csv("/content/drive/MyDrive/개인_프로젝트/titanic_PJT/train.csv", index_col=0)

# return이 어떻게 되는지 이해 할 것
df.fillna({'Age':df['Age'].mode()[0],
           'Embarked':df['Embarked'].mode()[0]}, inplace=True)
df_mode = df
df_mode = df_mode.drop(['Cabin'],axis=1)
# df_mode
# Cabin은 제거, 그외의 칼럼은 최빈값으로 대체한 df

In [54]:
df_mode
# df_mode.isnull().sum()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
PassengerId,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,24.0,1,2,W./C. 6607,23.4500,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [129]:
df = pd.read_csv("/content/drive/MyDrive/개인_프로젝트/titanic_PJT/train.csv")

# return이 어떻게 되는지 이해 할 것
df.fillna({'Age':round(df['Age'].mean()),
           'Embarked':df['Embarked'].mode()[0]},inplace=True)
df_mean_mode = df.drop('Cabin', axis=1)
# round(df['Age'].mean())
# Cabin은 제거, Age는 평균으로, Embarked는 최빈값으로 대체
# 반올림 하는 이유는 나이에 소수점은 없기 때문
df_mean_mode

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,30.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [177]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

df = pd.read_csv("/content/drive/MyDrive/개인_프로젝트/titanic_PJT/train.csv")
df.fillna({'Embarked':df['Embarked'].mode()[0]}, inplace=True)

imputer_mice = IterativeImputer(random_state=32)
# df_mice = pd.DataFrame(imputer_mice.fit_transform(df), columns=df.columns)
# 이상태로 하려면 수행이 안된다.

In [ ]:
df
# Name,PassengerId,Ticket

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### __select_dtypes 사용법__

* include 및 exclude는 비어있거나 겹치면 안되며(에러발생), 스칼라나 list형태의 입력값이 가능합니다.

---
- 숫자형(numeric)은 np.number 또는 'number'
- 문자형(str)은 'object'
- 날짜,시간(datetimes)을 선택하려면 np.datetime64, 'datetime' 또는 'datetime64'
- timedeltas는 np.timedelta64, 'timedelta' or 'timedelta64'
- Pandas의 categorical 타입은 'category'

In [180]:
df_number = df.select_dtypes('number')

In [181]:
df_mice = pd.DataFrame(imputer_mice.fit_transform(df_number), columns=df_number.columns)
df_mice

# 이상태로 수행하게 되면, Age타입이 float64이라 나이가 소수점으로 나오게 된다.
# 따라서 이를 방지하기 위해 int64로 변경해보자

     PassengerId  Survived  Pclass        Age  SibSp  Parch     Fare
0            1.0       0.0     3.0  22.000000    1.0    0.0   7.2500
1            2.0       1.0     1.0  38.000000    1.0    0.0  71.2833
2            3.0       1.0     3.0  26.000000    0.0    0.0   7.9250
3            4.0       1.0     1.0  35.000000    1.0    0.0  53.1000
4            5.0       0.0     3.0  35.000000    0.0    0.0   8.0500
..           ...       ...     ...        ...    ...    ...      ...
886        887.0       0.0     2.0  27.000000    0.0    0.0  13.0000
887        888.0       1.0     1.0  19.000000    0.0    0.0  30.0000
888        889.0       0.0     3.0  23.414502    1.0    2.0  23.4500
889        890.0       1.0     1.0  26.000000    0.0    0.0  30.0000
890        891.0       0.0     3.0  32.000000    0.0    0.0   7.7500

[891 rows x 7 columns]

In [182]:
# df_int = df_number.astype({'Age':'int'})
# null 이 포함되어 있을 때는 이를 방지하기 위해 임의값을 기입했다가 다시 Null로 변경해줘야한다.

df_number['Age'] = df_number['Age'].fillna(3).astype(int).replace({3:None})
df_number.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Age             object
SibSp            int64
Parch            int64
Fare           float64
dtype: object

In [183]:
df_mice = pd.DataFrame(imputer_mice.fit_transform(df_number), columns=df_number.columns)
df_mice
# 내가 지금 필요한 것은 mice 대체를 통해 소수점이 없는 자료를 만드는 것임..

df_mice['Age'] = df_mice['Age'].round(decimals=0)

In [184]:
df_mice.dtypes
# 왜 근데 다시 float형으로 변한거지??
df_mice = df_mice.astype(int)
df_mice.dtypes

PassengerId    int64
Survived       int64
Pclass         int64
Age            int64
SibSp          int64
Parch          int64
Fare           int64
dtype: object

In [188]:
dff = df.select_dtypes('object')
dff.head()

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S

In [189]:
df_22 = df_mice
df_22[dff.columns] = dff[dff.columns]

In [187]:
# df_22 = df_22.drop(labels='Cabin',axis=1)
# 전처리 완료
df_22.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Age            0
SibSp          0
Parch          0
Fare           0
dtype: int64

# 데이터 모델링

현재 세가지 데이터 셋을 준비하였다.
- 1. df_mode : cabin 제거, 최빈값 대체
- 2. df_mean_mode : cabin 제거, Age 평균 반올림 대체, Embarked 최빈값 대체
- 3. df_22 : cabin 제거, Age mice 반올림 대체, Embarked 최빈값 대체

## LogisticRegression

### df_mode

In [116]:
indict1 = False
indict2 = False

In [284]:
from sklearn.model_selection import train_test_split

df_mode = df_mode.reset_index()
# reset_index 하는 이유는 불필요한 index가 발생하는데
# 이것 때문에 fit할 때 에러가 발생함...

# ['female', 'male']
if indict1 == False:
  for i in range(len(df_mode['Sex'])):
    if df_mode['Sex'][i] == 'female':
      df_mode['Sex'][i] = 1
    else:
      df_mode['Sex'][i] = 0
  indict1 = True
else:
  pass

# ['S', 'C', 'Q']
if indict2 == False:
  for i in range(len(df_mode['Embarked'])):
    if i == 'S':
      df_mode['Embarked'][i] = 0
    elif i == 'C':
      df_mode['Embarked'][i] = 1
    else:
      df_mode['Embarked'][i] = 2
  indict2 = True
else:
  pass
indict2 # True가 나오면 변환 완료 된 것 임


X_train, X_test, y_train, y_test = train_test_split(
    df_mode.drop(["Survived","Name","Ticket"], axis=1),
    df_mode['Survived'],
    random_state=42,
    stratify=df_mode['Survived']
)

In [285]:
from sklearn.linear_model import LogisticRegression


model = LogisticRegression(max_iter=500)
model.fit(X_train, y_train)

LogisticRegression(max_iter=500)

In [286]:
from sklearn.metrics import accuracy_score

lr_pred = model.predict(X_test)
accuracy_score(lr_pred, y_test), recall_score(lr_pred, y_test), f1_score(lr_pred, y_test)

(0.7713004484304933, 0.7058823529411765, 0.7017543859649124)

### 앞서 만들어둔, 명목척도로 변환하는 알고리즘을 def화 하도록 하자...

In [156]:
def change_nominal(dataframe, list, tmp1, tmp2):
  dataframe = dataframe.reset_index()
  for i in list:
    for j in range(len(dataframe[i])):
      for k in tmp2:
        if dataframe[i][j] == k:
          dataframe[i][j] = tmp1[k]
  return dataframe

In [159]:
def make_nominal(dataframe, list):
  dataframe = dataframe.reset_index()
  tmp1 = {}
  tmp2 = []
  index = 0

  for i in list:
    for idx in dataframe[i]:
      if idx not in tmp1:
        tmp1[idx] = index
        tmp2.append(idx)
        index += 1
    index = 0
  return change_nominal(dataframe, list, tmp1, tmp2)

### df_mean_mode

In [199]:
df_mean_mode = make_nominal(df_mean_mode, ['Sex','Embarked'])

ValueError: cannot insert level_0, already exists

In [281]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df_mean_mode.drop(["Survived","Name","Ticket"], axis=1),
    df_mean_mode['Survived'],
    random_state=42,
    stratify=df_mean_mode['Survived']
)

In [282]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter = 5000)
model.fit(X_train,y_train)

LogisticRegression(max_iter=5000)

In [283]:
from sklearn.metrics import accuracy_score

lr_pred = model.predict(X_test)
accuracy_score(lr_pred, y_test), recall_score(lr_pred, y_test), f1_score(lr_pred, y_test)
# 기존 값보다는 올랐다..

(0.7757847533632287, 0.7307692307692307, 0.6951219512195121)

### df_22

In [205]:
df_22 = make_nominal(df_22, ['Sex','Embarked'])

ValueError: cannot insert level_0, already exists

In [206]:
df_22 = df_22.drop('Cabin', axis=1)

KeyError: "['Cabin'] not found in axis"

In [280]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, recall_score

X_train, X_test, y_train, y_test = train_test_split(
    df_22.drop(["Survived","Name","Ticket"], axis=1),
    df_22['Survived'],
    random_state=42,
    stratify=df_22['Survived']
)

model = LogisticRegression(max_iter = 5000)
model.fit(X_train,y_train)

lr_pred = model.predict(X_test)
accuracy_score(lr_pred, y_test), recall_score(lr_pred, y_test), f1_score(lr_pred, y_test)

(0.7982062780269058, 0.7530864197530864, 0.7305389221556886)

### LogisticRegression에서의 점수 비교
3가지 전처리 자료를 비교했을 대,
각각
```
  df_mode = 77.13%
  df_mean_mode = 77.58%
  df_22 = 79.82%
```
로 나타났다.

## DecisionTree

In [294]:
from sklearn.tree import DecisionTreeClassifier

X_train, X_test, y_train, y_test = train_test_split(
    df_mode.drop(["Survived","Name","Ticket"], axis=1),
    df_mode['Survived'],
    random_state=42,
    stratify=df_mode['Survived']
)

max_acc = 0

for i in range(1):
  dt_clf = DecisionTreeClassifier(max_depth=5)
  dt_clf.fit(X_train, y_train)
  dt_pred = dt_clf.predict(X_test)

  acc = accuracy_score(dt_pred,y_test)
  if acc > max_acc:
    max_acc = acc
    max_i = i

round(accuracy_score(dt_pred, y_test) * 100,3), round(recall_score(dt_pred, y_test) * 100,3), round(f1_score(dt_pred, y_test) * 100,3)

# max_depth = 5일때 가장 높게 나온다.

(72.197, 63.333, 64.773)

In [293]:
from sklearn.tree import DecisionTreeClassifier

X_train, X_test, y_train, y_test = train_test_split(
    df_mean_mode.drop(["Survived","Name","Ticket"], axis=1),
    df_mean_mode['Survived'],
    random_state=42,
    stratify=df_mean_mode['Survived']
)

max_acc = 0

for i in range(1):
  dt_clf = DecisionTreeClassifier(max_depth=3)
  dt_clf.fit(X_train, y_train)
  dt_pred = dt_clf.predict(X_test)

  acc = accuracy_score(dt_pred,y_test)
  if acc > max_acc:
    max_acc = acc
    max_i = i
round(max_acc * 100,5), max_i
round(accuracy_score(dt_pred, y_test) * 100,3), round(recall_score(dt_pred, y_test) * 100,3), round(f1_score(dt_pred, y_test) * 100,3)

# max_depth = 5일때 가장 높게 나온다.

(77.578, 84.615, 63.768)

In [292]:
from sklearn.tree import DecisionTreeClassifier

X_train, X_test, y_train, y_test = train_test_split(
    df_22.drop(["Survived","Name","Ticket"], axis=1),
    df_22['Survived'],
    random_state=42,
    stratify=df_22['Survived']
)

max_acc = 0

for i in range(1):
  dt_clf = DecisionTreeClassifier(max_depth=5)
  dt_clf.fit(X_train, y_train)
  dt_pred = dt_clf.predict(X_test)

  acc = accuracy_score(dt_pred,y_test)
  if acc > max_acc:
    max_acc = acc
    max_i = i
round(max_acc * 100,5), max_i
round(accuracy_score(dt_pred, y_test) * 100,3), round(recall_score(dt_pred, y_test) * 100,3), round(f1_score(dt_pred, y_test) * 100,3)

# max_depth = 5일때 가장 높게 나온다.

(82.063, 80.263, 75.309)

### DecisionTreeClassifier에서 점수 비교

```python
  df_mode = (72.197, 63.333, 64.773)
  df_mean_mode = (77.578, 84.615, 63.768)
  df_22 = (82.063, 80.263, 75.309)


```
전반적으로 mice를 사용한 데이터에서 점수가 높게 나온다.

## RandomForest

In [318]:
from sklearn.tree import DecisionTreeClassifier

X_train, X_test, y_train, y_test = train_test_split(
    df_mode.drop(["Survived","Name","Ticket"], axis=1),
    df_mode['Survived'],
    random_state=42,
    stratify=df_mode['Survived']
)
max_f1 = 0
for i in range(10,500,10):
  fr_clf = RandomForestClassifier(n_estimators=i , random_state=42)
  fr_clf.fit(X_train,y_train)

  fr_pred = fr_clf.predict(X_test)
  if f1_score(fr_pred, y_test) * 100 > max_f1:
    max_f1 = round(f1_score(fr_pred, y_test) * 100 , 3)
    max_acc = round(accuracy_score(fr_pred, y_test) * 100, 3)
    max_rec = round(recall_score(fr_pred, y_test) * 100 , 3)
  print(i)
print(max_acc, max_rec, max_f1)

10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300
310
320
330
340
350
360
370
380
390
400
410
420
430
440
450
460
470
480
490
78.924 74.684 71.515

In [319]:
from sklearn.tree import DecisionTreeClassifier

X_train, X_test, y_train, y_test = train_test_split(
    df_mean_mode.drop(["Survived","Name","Ticket"], axis=1),
    df_mean_mode['Survived'],
    random_state=42,
    stratify=df_mean_mode['Survived']
)

max_f1 = 0
for i in range(10,500,10):
  fr_clf = RandomForestClassifier(n_estimators=i , random_state=42)
  fr_clf.fit(X_train,y_train)

  fr_pred = fr_clf.predict(X_test)
  if f1_score(fr_pred, y_test) * 100 > max_f1:
    max_f1 = round(f1_score(fr_pred, y_test) * 100 , 3)
    max_acc = round(accuracy_score(fr_pred, y_test) * 100, 3)
    max_rec = round(recall_score(fr_pred, y_test) * 100 , 3)
  print(i)
print(max_acc, max_rec, max_f1)

10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300
310
320
330
340
350
360
370
380
390
400
410
420
430
440
450
460
470
480
490
79.821 76.623 72.393

In [322]:
from sklearn.ensemble import RandomForestClassifier

X_train, X_test, y_train, y_test = train_test_split(
    df_22.drop(["Survived","Name","Ticket"], axis=1),
    df_22['Survived'],
    random_state=42,
    stratify=df_22['Survived']
)
max_f1 = 0
for i in range(10,500,4):
  fr_clf = RandomForestClassifier(n_estimators=i , random_state=42)
  fr_clf.fit(X_train,y_train)

  fr_pred = fr_clf.predict(X_test)
  if f1_score(fr_pred, y_test) * 100 > max_f1:
    max_f1 = round(f1_score(fr_pred, y_test) * 100 , 3)
    max_acc = round(accuracy_score(fr_pred, y_test) * 100, 3)
    max_rec = round(recall_score(fr_pred, y_test) * 100 , 3)
  print(i)
print(max_acc, max_rec, max_f1)

10
14
18
22
26
30
34
38
42
46
50
54
58
62
66
70
74
78
82
86
90
94
98
102
106
110
114
118
122
126
130
134
138
142
146
150
154
158
162
166
170
174
178
182
186
190
194
198
202
206
210
214
218
222
226
230
234
238
242
246
250
254
258
262
266
270
274
278
282
286
290
294
298
302
306
310
314
318
322
326
330
334
338
342
346
350
354
358
362
366
370
374
378
382
386
390
394
398
402
406
410
414
418
422
426
430
434
438
442
446
450
454
458
462
466
470
474
478
482
486
490
494
498
82.063 80.263 75.309

### RandomForest의 수행방식은 어떻게 될까?
먼저 배깅(Bagging)에 대해 알아보자면,

배깅(Bagging)은 Bootstrap Aggregating의 약자로, 보팅(Voting)과는 달리 동일한 알고리즘으로 여러 분류기를 만들어 보팅으로 최종 결정하는 알고리즘이다.

배깅의 진행방식은,

1. 동일한 알고리즘을 사용하는 일정 수의 분류기 생성
2. 각각의 분류기는 `*`부트스트래핑(Bootstrapping)방식으로 생성된 샘플데이터를 학습
3. 최종적으로 모든 분류기가 보팅을 통헤 예측 결정

`*` 부트스트래핑 샘플링은 전체 데이터에서 일부 데이터의 중첩을 허용하는 방식

### 랜덤포레스트 (RandomForest)
- 랜덤 포레스트는 여러 개의 결정트리(Decision Tree)를 활용한 배깅 방식의 대표적인 알고리즘

1. 장점
- 결정 트리의 쉽고 직관적인 장점을 그대로 가지고 있음
- 앙상블 알고리즘 중 비교적 빠른 수행 속도를 가지고 있음
- 다양한 분야에서 좋은 성능을 나타냄
2. 단점
- 하이퍼 파라미터가 많아 튜닝을 위힌 시간이 많이 소요됨

### RandomForest에서의 점수비교

```python
  df_mode = (78.924 74.684 71.515)
  df_mean_mode = (79.821 76.623 72.393)
  df_22 = (82.063 80.263 75.309)
```
mice 처리한 데이터에서 이번에도 가장 높게 점수가 나왔다.

이전에 수행한 내역과 비교했을 때, df_22에서 DecisionTree와 동일한 점수가 나왔다. 왜 그런 것인가에 대해 조사해보았다.

---

randomforest는 DecisionTree를 기반한 머신러닝이다.
엄밀히는, 랜덤포레스트가 진행될 때 `의사결정트리`를 이용해 만들어진 것을 여러개의 `의사결정트리`를 만들고, 투표를 시켜 다수결로 결과를 결정하는 방법이기 때문이다.

그런데 만약에 그렇다고하면, DecisionTree에서 나온 가장 좋은 값이 Randomforest보다 좋다고 할 수 있을까?

반대의 경우를 생각해본다면 어떻게 말해야할까?